In [27]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
#Read the data which is in tsv format
dataFrame = pd.read_csv("version1/modeldata1.tsv", sep='\t')

In [29]:
dataFrame

post_uniqueId  \
0     10018424053942873889082198747912907137   
1     10026850716042389556576263521924262981   
2     10032048104037663246053508571238522490   
3     10037812214202385317397104575584028455   
4     10073685915684371025126228621365391683   
5     10084050799645558924394285035561227652   
6     10090508707793678148010809163669860386   
7      1014823069263187570542639789830811546   
8     10154333302448123001296296030949807006   
9     10160820624558160512046813118126678019   
10    10179179075223186102109838508973523894   
11    10247928269329322372267305037484558810   
12    10250474667431045952961007694782875117   
13    10251716788760177831646941199380221547   
14    10257725713517392342549423315345165350   
15    10299711866648945795948516688412950754   
16      103113442627283021618594033323092422   
17     1032797726619653657552216692467329966   
18    10328713767697740446351160985222698483   
19    10329600587210561378426676756417599496   
20    10343239896723367217769522140678667760   
21    10388227158950646763677300372977880374   
22    10438417299565088596140984145103884054   
23    10458157021151659915992748295101741303   
24    10478583922201298615320891751074272352   
25     1051075787788863967370558326390519683   
26    10510837567905425131652326494405736340   
27     1052072907581026934570421600712885891   
28    10523433843024824865187402666541643251   
29    10572159673769129002682617093496192718   
...                                      ...   
4004    924660530508398646246964797970099436   
4005    926060844614265277563616483339310745   
4006   9261311825563336282766855796834152088   
4007   9298067523297575166306059188481669104   
4008   9344505676330188992401252745362118728   
4009    934643011941628288561578236330441642   
4010     93730885455477076070809116254579798   
4011   9399547300793740063821699109333679094   
4012   9416837005792546777242131717862377916   
4013    942805669521645556550018208616158878   
4014   9437704253141242911821018743796924237   
4015   9475814994371524523112908450117158244   
4016   9487389771389947973106378608778336353   
4017   9491125696236587793828310658562409348   
4018   9493909340237471834025341810420835587   
4019   9584913517569000695532278289639480987   
4020   9642490248224288105293267758023389852   
4021   9647505354072816746120970494956373763   
4022   9656604084719838406285814411302513989   
4023    969931872439639432124287860501182818   
4024    971185947092380576759346078998500292   
4025   9718891040032607146473248286375847826   
4026   9741398239346275831136942146498913261   
4027    974644887000282429614760535362580426   
4028   9817647420442455693569981291178959568   
4029   9818547384187768201376474682928211048   
4030   9869827414061678635367814828357918318   
4031   9894263340574783132199356841906445261   
4032   9946658007725446987354084049172505038   
4033   9965285808428150201060045888337809366   

                                        post_event_list country  \
0     197,131,20110=1.00,107,222,10008,158,175,285,5...     usa   
1     197,131,222,107,109,175,212,169,525,163,248,20...     usa   
2     292:4810471238521usbsd,197,131,222,107,101,169...     usa   
3     197,131,222,107,171,169,525,163,248,139,110,10...     usa   
4     197,131,222,169,525,163,248,195,110,10001,147,...     usa   
5     197,131,222,175,171,169,20103=1.00,163,525,248...     usa   
6     197,131,106,107,10005,109,212,525,163,248,110,...     usa   
7     197,131,222,107,20117,109,285,290=42.19,262=11...     can   
8     197,131,222,107,171,169,525,163,248,110,10001,...     usa   
9     197,131,222,107,285,292:2062418126676usdhs,293...     usa   
10    197,131,222,107,175,171,169,262=64.00,163,525,...     usa   
11    197,131,222,109,525,163,248,294:28269374845513...     usa   
12    197,131,123,107,262=293.64,169,525,163,101,248...     gbr   
13    292:1678899380227usbsd,197,131,10005,222,525,1...     usa   
14    197,131,222,107,169,525,163,101,248,139,110

In [30]:
#load all the columns which effect the purchase of the user
x = dataFrame.iloc[:,2:48 ].values

In [31]:
#Dislaying array x
x

array([['usa', 949, 1920, ..., 1, 0, 1],
       ['usa', 769, 1600, ..., 1, 0, 0],
       ['usa', 553, 375, ..., 0, 0, 1],
       ...,
       ['can', 905, 1817, ..., 0, 0, 0],
       ['usa', 804, 1140, ..., 0, 0, 1],
       ['usa', 641, 913, ..., 0, 0, 0]], dtype=object)

In [32]:
#Loading the dependent column values i.e purchased column which describes if a user made a purchase or not
y = dataFrame.loc[:, ['purchased']].values

In [33]:
#column country is categorical data, which needs to be converted into numerical values using labels
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [34]:
#Labelling the categorical data. In this case we are using coulumn 0, which is country
xLabelEncoder = LabelEncoder()
x[:, 0] = xLabelEncoder.fit_transform(x[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
x = onehotencoder.fit_transform(x).toarray()

In [35]:
#Displaying x
x

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
x.shape

(4034, 86)

In [37]:
#Loading library
from sklearn.model_selection import train_test_split

In [38]:
#Split array into random train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
#Scaling the values for easier computations.
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [41]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [42]:
#We are using a sequential model
model = Sequential()

In [43]:
#first input layer
#units replace output_dim, init is replaced by kernel_initializer
model.add(Dense(units = 44, kernel_initializer="uniform", activation = 'relu', input_dim = 86))

In [44]:
#adding hidden layer
model.add(Dense(units = 44, kernel_initializer="uniform", activation = 'relu'))
model.add(Dense(units = 44, kernel_initializer="uniform", activation = 'relu'))

In [45]:
#adding output layer
model.add(Dense(units = 1, kernel_initializer="uniform", activation = 'sigmoid'))

In [46]:
#compiling artificial neural network
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [108]:
#fit artificial neural network to training set
model.fit(x_train, y_train, batch_size = 100, epochs = 150)

Epoch 1/150
3025/3025 [==============================] - 0s 31us/step - loss: 0.0064 - acc: 0.9974
Epoch 2/150
3025/3025 [==============================] - 0s 23us/step - loss: 0.0057 - acc: 0.9970
Epoch 3/150
3025/3025 [==============================] - 0s 29us/step - loss: 0.0057 - acc: 0.9974
Epoch 4/150
3025/3025 [==============================] - 0s 33us/step - loss: 0.0054 - acc: 0.9977
Epoch 5/150
3025/3025 [==============================] - 0s 28us/step - loss: 0.0064 - acc: 0.9967
Epoch 6/150
3025/3025 [==============================] - 0s 23us/step - loss: 0.0059 - acc: 0.9967
Epoch 7/150
3025/3025 [==============================] - 0s 23us/step - loss: 0.0059 - acc: 0.9970
Epoch 8/150
3025/3025 [==============================] - 0s 25us/step - loss: 0.0056 - acc: 0.9967
Epoch 9/150
3025/3025 [==============================] - 0s 23us/step - loss: 0.0055 - acc: 0.9970
Epoch 10/150
3025/3025 [==============================] - 0s 23us/step - loss: 0.0063 - acc: 0.9970
Epoch 11/

Epoch 83/150
3025/3025 [==============================] - 0s 31us/step - loss: 0.0066 - acc: 0.9977
Epoch 84/150
3025/3025 [==============================] - 0s 28us/step - loss: 0.0054 - acc: 0.9970
Epoch 85/150
3025/3025 [==============================] - 0s 34us/step - loss: 0.0073 - acc: 0.9974
Epoch 86/150
3025/3025 [==============================] - 0s 25us/step - loss: 0.0053 - acc: 0.9983
Epoch 87/150
3025/3025 [==============================] - 0s 34us/step - loss: 0.0057 - acc: 0.9970
Epoch 88/150
3025/3025 [==============================] - 0s 24us/step - loss: 0.0046 - acc: 0.9983
Epoch 89/150
3025/3025 [==============================] - 0s 15us/step - loss: 0.0047 - acc: 0.9980
Epoch 90/150
3025/3025 [==============================] - 0s 21us/step - loss: 0.0041 - acc: 0.9977
Epoch 91/150
3025/3025 [==============================] - 0s 25us/step - loss: 0.0035 - acc: 0.9987
Epoch 92/150
3025/3025 [==============================] - 0s 22us/step - loss: 0.0039 - acc: 0.9980


In [130]:
#Predicting results from test set
y_pred = model.predict(x_test)

In [131]:
y_pred

array([[3.0981327e-35],
       [1.0000000e+00],
       [3.7715972e-24],
       ...,
       [0.0000000e+00],
       [2.5994975e-38],
       [8.9470844e-12]], dtype=float32)

In [122]:
#Converting to boolean either true or false
y_pred = (y_pred > 0.5)

In [123]:
from sklearn.metrics import confusion_matrix

In [124]:
confusionMatrix = confusion_matrix(y_test,y_pred)

In [125]:
#To check the accuracy
confusionMatrix

array([[818,  11],
       [ 14, 166]], dtype=int64)

In [126]:
(818+166)/1009

0.9752229930624381

In [135]:
y_pred_maybe = (y_pred < 0.2)

In [136]:
type(y_pred_maybe)

numpy.ndarray

In [137]:
np.sum(y_pred_maybe)

830

In [ ]:
confusionMatrix = confusion_matrix(y_test,y_pred)